CREATE TABLE "COM"."EMPLOYETB"
(
   CODESO char(2) DEFAULT ' ' NOT NULL,
   CODEVE char(8) DEFAULT ' ' NOT NULL,
   MATRCL smallint DEFAULT 0 NOT NULL,
   DATCRE date NOT NULL,
   QUICRE char(8) DEFAULT ' ' NOT NULL,
   TMSMAJ timestamp NOT NULL,
   QUIMAJ char(8) DEFAULT ' ' NOT NULL,
   NOMUTI char(64) DEFAULT ' ' NOT NULL,
   NOMSVC char(64) DEFAULT ' ' NOT NULL
)
;
CREATE INDEX EMPLOYEI1 ON "COM"."EMPLOYETB"
(
  NOMUTI,
  NOMSVC
)
;
CREATE UNIQUE INDEX EMPLOYEI0 ON "COM"."EMPLOYETB"
(
  CODEVE,
  MATRCL,
  CODESO
)
;
-- etc...
