version:                       '3.2'

services:
  db:
    build:                     ./docker-build/db2
    cap_add:
      - IPC_LOCK
      - IPC_OWNER
    ports:
      - 50000:50000
    environment:
          DB2INSTANCE:         db2inst1
          DB2INST1_PASSWORD:   thisisthepwd
          LICENSE:             accept
    command:                   su - db2inst1 -c "db2start"
